# Generated by Django 4.1.7 on 2023-04-12 23:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscribe", "0003_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="data",
            field=models.IntegerField(),
        ),
    ]
