# Generated by Django 4.1.7 on 2023-04-12 23:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscribe", "0005_alter_entry_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="data",
            field=models.FloatField(),
        ),
    ]
