# Generated by Django 4.1.7 on 2023-04-13 00:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscribe", "0006_alter_entry_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="Entry2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(max_length=255)),
                ("data", models.FloatField()),
                ("pub_date", models.DateField()),
            ],
        ),
    ]
