# Generated by Django 4.1.7 on 2023-04-13 21:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscribe", "0007_entry2"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscriptions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255)),
                ("sensorX", models.BooleanField(default=False)),
                ("sensorY", models.BooleanField(default=False)),
                ("sensorZ", models.BooleanField(default=False)),
            ],
        ),
    ]
