# Generated by Django 4.1.7 on 2023-04-14 20:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscribe", "0008_subscriptions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry2",
            name="pub_date",
            field=models.DateTimeField(),
        ),
    ]
