name: Django CI

on:
  push:
    branches: [ main, CI ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9, 3.11]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        pip install django
        pip install paho-mqtt
    - name: Setup DB
      run: |
      working-directory: sensingGang
        python manage.py migrate
    - name: Run Tests
      working-directory: sensingGang
      run: |
        python manage.py test
